"""GitHub CLI (gh) wrapper with per-account isolation.

Each GitHub account gets its own HOME / GH_CONFIG_DIR under DATA_DIR so
multiple accounts can be used side by side. Authentication is injected via
GH_TOKEN. SSH keys generated by `gh codespace ssh` are persisted to MongoDB
and restored to disk before every command.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import shlex
import subprocess
from pathlib import Path

import aiohttp

log = logging.getLogger(__name__)

# Official GitHub CLI OAuth app client ID (same one `gh auth login` uses).
GH_OAUTH_CLIENT_ID = "178c6fc778ccc68e1d6a"
GH_OAUTH_SCOPES = "repo codespace read:org"

SSH_KEY_NAME = "codespaces.auto"


class GhError(RuntimeError):
    """Raised when a gh CLI or GitHub API call fails."""


class Gh:
    def __init__(self, settings, db) -> None:
        self.settings = settings
        self.db = db

    # ------------------------------------------------------------------
    # Per-account environment
    # ------------------------------------------------------------------

    def account_home(self, account: dict) -> Path:
        home = Path(self.settings.data_dir) / "accounts" / str(account["_id"])
        home.mkdir(parents=True, exist_ok=True)
        return home

    def _restore_ssh_keys(self, account: dict, home: Path) -> None:
        try:
            home.chmod(0o700)
        except Exception:
            pass
        ssh_dir = home / ".ssh"
        ssh_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
        try:
            ssh_dir.chmod(0o700)
        except Exception:
            pass

        config_file = ssh_dir / "config"
        config_content = (
            "Host *\n"
            "  StrictHostKeyChecking no\n"
            "  UserKnownHostsFile /dev/null\n"
            "  LogLevel ERROR\n"
        )
        config_file.write_text(config_content)
        try:
            config_file.chmod(0o600)
        except Exception:
            pass

        known_hosts = ssh_dir / "known_hosts"
        if not known_hosts.exists():
            known_hosts.write_text("")
        try:
            known_hosts.chmod(0o600)
        except Exception:
            pass

        priv = account.get("ssh_private_key")
        pub = account.get("ssh_public_key")
        priv_path = ssh_dir / SSH_KEY_NAME
        pub_path = ssh_dir / f"{SSH_KEY_NAME}.pub"

        if priv and priv.strip() and pub and pub.strip():
            priv_path.write_text(priv)
            pub_path.write_text(pub)
        else:
            if priv_path.exists() and priv_path.stat().st_size == 0:
                priv_path.unlink(missing_ok=True)
            if pub_path.exists() and pub_path.stat().st_size == 0:
                pub_path.unlink(missing_ok=True)

            if not priv_path.exists() or not pub_path.exists():
                try:
                    subprocess.run(
                        ["ssh-keygen", "-t", "ed25519", "-N", "", "-C", "codespace-keeper", "-f", str(priv_path)],
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                        check=True,
                    )
                except Exception:
                    try:
                        subprocess.run(
                            ["ssh-keygen", "-t", "rsa", "-b", "3072", "-N", "", "-C", "codespace-keeper", "-f", str(priv_path)],
                            stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL,
                            check=True,
                        )
                    except Exception:
                        pass

        if priv_path.exists():
            try:
                priv_path.chmod(0o600)
            except Exception:
                pass
        if pub_path.exists():
            try:
                pub_path.chmod(0o644)
            except Exception:
                pass

    def _env(self, account: dict) -> dict:
        home = self.account_home(account)
        (home / ".config" / "gh").mkdir(parents=True, exist_ok=True)
        self._restore_ssh_keys(account, home)
        env = dict(os.environ)
        env.update(
            {
                "HOME": str(home),
                "GH_CONFIG_DIR": str(home / ".config" / "gh"),
                "GH_TOKEN": account["token"],
                "GH_PROMPT_DISABLED": "1",
                "GH_NO_UPDATE_NOTIFIER": "1",
            }
        )
        return env

    async def _persist_ssh_keys(self, account: dict) -> None:
        """Store freshly generated SSH keys in MongoDB."""
        if account.get("ssh_private_key") and account.get("ssh_public_key"):
            return
        ssh_dir = self.account_home(account) / ".ssh"
        priv_path = ssh_dir / SSH_KEY_NAME
        pub_path = ssh_dir / f"{SSH_KEY_NAME}.pub"
        if priv_path.exists() and pub_path.exists():
            priv = priv_path.read_text().strip()
            pub = pub_path.read_text().strip()
            if priv and pub:
                await self.db.set_ssh_keys(account["_id"], priv, pub)
                account["ssh_private_key"] = priv
                account["ssh_public_key"] = pub
                log.info("Stored SSH keys for account %s", account.get("login"))

    # ------------------------------------------------------------------
    # gh CLI execution
    # ------------------------------------------------------------------

    async def run(self, account: dict, args: list[str], timeout: int = 180) -> tuple[int, str]:
        proc = await asyncio.create_subprocess_exec(
            "gh",
            *args,
            env=self._env(account),
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        try:
            out, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        except asyncio.TimeoutError:
            proc.kill()
            raise GhError(f"`gh {' '.join(args[:3])} ...` timed out after {timeout}s")
        text = (out or b"").decode(errors="replace").strip()
        await self._persist_ssh_keys(account)
        return proc.returncode or 0, text

    # ------------------------------------------------------------------
    # Codespaces
    # ------------------------------------------------------------------

    async def list_codespaces(self, account: dict) -> list[dict]:
        rc, out = await self.run(
            account,
            ["codespace", "list", "--json", "name,displayName,repository,state"],
        )
        if rc != 0:
            raise GhError(out or "Failed to list codespaces")
        try:
            return json.loads(out or "[]")
        except json.JSONDecodeError as exc:
            raise GhError(f"Unexpected gh output: {out[:300]}") from exc

    async def get_codespace_state(self, account: dict, name: str) -> str:
        rc, out = await self.run(account, ["codespace", "list", "--json", "name,state"])
        if rc != 0:
            raise GhError(out or "Failed to query codespace state")
        for item in json.loads(out or "[]"):
            if item.get("name") == name:
                return item.get("state") or "Unknown"
        raise GhError(f"Codespace {name} no longer exists")

    async def stop_codespace(self, account: dict, name: str) -> None:
        """Stop (shut down) a codespace."""
        rc, out = await self.run(account, ["codespace", "stop", "-c", name])
        if rc != 0:
            low = (out or "").lower()
            if "is not running" in low or "already stopped" in low or "not running" in low:
                log.info("Codespace %s is already stopped", name)
                return
            raise GhError(out or f"Failed to stop codespace {name}")

    async def start_codespace(self, account: dict, name: str) -> dict:
        """Start a codespace directly via GitHub REST API."""
        url = f"https://api.github.com/user/codespaces/{name}/start"
        headers = {
            "Authorization": f"Bearer {account['token']}",
            "Accept": "application/vnd.github+json",
        }
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers) as resp:
                if resp.status in (200, 201, 202, 204):
                    try:
                        return await resp.json()
                    except Exception:
                        return {}
                text = await resp.text()
                raise GhError(f"API start failed (HTTP {resp.status}): {text[:200]}")

    async def ssh_exec(
        self, account: dict, name: str, command: str, timeout: int = 300
    ) -> tuple[int, str]:
        """Run a shell command inside the codespace over SSH.

        Connecting via `gh codespace ssh` automatically starts a stopped
        codespace and counts as activity, which resets GitHub's idle timer.
        """
        args = [
            "codespace",
            "ssh",
            "-c",
            name,
            "--",
            "-o",
            "StrictHostKeyChecking=no",
            "-o",
            "UserKnownHostsFile=/dev/null",
            "-o",
            "LogLevel=ERROR",
            f"bash -lc {shlex.quote(command)}",
        ]
        return await self.run(account, args, timeout=timeout)

    # ------------------------------------------------------------------
    # Authentication helpers
    # ------------------------------------------------------------------

    async def token_login(self, token: str) -> str:
        """Validate a token and return the GitHub login it belongs to."""
        async with aiohttp.ClientSession() as session:
            async with session.get(
                "https://api.github.com/user",
                headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                },
            ) as resp:
                if resp.status != 200:
                    raise GhError(
                        f"Token check failed (HTTP {resp.status}). "
                        "Make sure the token is valid and has the right scopes."
                    )
                data = await resp.json()
        return data["login"]

    async def device_code_start(self) -> dict:
        """Start the GitHub device login flow (same flow `gh auth login` uses)."""
        async with aiohttp.ClientSession() as session:
            async with session.post(
                "https://github.com/login/device/code",
                data={"client_id": GH_OAUTH_CLIENT_ID, "scope": GH_OAUTH_SCOPES},
                headers={"Accept": "application/json"},
            ) as resp:
                data = await resp.json()
        if "device_code" not in data:
            raise GhError(f"Could not start device login: {data}")
        return data

    async def device_code_poll(self, device_code: str, interval: int, expires_in: int) -> str:
        loop = asyncio.get_event_loop()
        deadline = loop.time() + min(expires_in, 900)
        wait = max(int(interval or 5), 5)
        async with aiohttp.ClientSession() as session:
            while loop.time() < deadline:
                await asyncio.sleep(wait)
                async with session.post(
                    "https://github.com/login/oauth/access_token",
                    data={
                        "client_id": GH_OAUTH_CLIENT_ID,
                        "device_code": device_code,
                        "grant_type": "urn:ietf:params:oauth:grant-type:device_code",
                    },
                    headers={"Accept": "application/json"},
                ) as resp:
                    data = await resp.json()
                if data.get("access_token"):
                    return data["access_token"]
                error = data.get("error")
                if error == "authorization_pending":
                    continue
                if error == "slow_down":
                    wait += 5
                    continue
                raise GhError(data.get("error_description") or error or "Device login failed")
        raise GhError("Device login timed out. Please try again.")
